# GEOG310, Lab 01, Introduction to JupyterLab, notebooks, and Python - Part 2

This notebook introduces the basic environment of Jupyter, allows you to get familiar with some commands, and get you started on your independent exploration

Logging into see-trx4001
    
Step 1: open a user account using powershell on windows or linux/mac terminal
    
Step 2: secure shell into see-trx4001 linux computer
        ***ssh usr123@see-trx4001.canterbury.ac.nz*** then hit enter
    
Step 3: use your internet browser to log into the JupyterLab server
        ***https://see-trx4001.canterbury.ac.nz:9552/***

**What is a JupyterLab?**
From https://jupyter.org/try-jupyter/retro/notebooks/?path=notebooks/Intro.ipynb
JupyterLab is a next-generation web-based user interface for Project Jupyter. It enables you to work with documents and activities such as Jupyter notebooks, text editors, terminals, and custom components in a flexible, integrated, and extensible manner. It is the interface that you're looking at right now.

**What is a Jupyter Notebook?**
From https://jupyter.org/try-jupyter/retro/notebooks/?path=notebooks/Intro.ipynb
Jupyter Notebooks are a community standard for communicating and performing interactive computing. They are a document that blends computations, outputs, explanatory text, mathematics, images, and rich media representations of objects.

**Jupyter Notebooks are notebooks that combine live runnable code with narrative text**

For further documentation and help on JupyterLab
https://jupyterlab.readthedocs.io/en/stable/user/index.html

# Section 1. Array Manipulation
Numpy is "The fundamental package for scientific computing with Python". (https://numpy.org)

### Section 1.1. Importing Libraries

In [ ]:
### Libraries are existing packages of functions/classes written by you or someone else. You can utilize the existing functions to speed up your work.

In [34]:
import numpy as np # import all the library

In [35]:
from numpy import sqrt as npsqrt # import a specific operation

In [36]:
np.sqrt(20) # This way is more flexible...

4.47213595499958

In [37]:
np.sqrt(50)

7.0710678118654755

In [48]:
# dont forget that you list all functions in the library using:
dir(np) # remember that numpy is imported as np now.

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

### Section 1.2. Creating an Array

In [49]:
vector=np.array([0,1,2,3,4,5,6,7,8,9,10])

In [50]:
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a = np.arange(0,11,1) #is a function used to create an array with regularly spaced values within a specified range.
# np.arange(start,stop,step)

In [33]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
#Task: Explore what the numpy function linspace does


In [ ]:
#Task: explore what the numpy functions ones and zeros do

In [ ]:
# creating 2 dimensional arrays

In [9]:
A=np.array([[5,10,15],[10,20,30]])

In [10]:
A

array([[ 5, 10, 15],
       [10, 20, 30]])

In [83]:
a=np.array([[20,30,40],[50,60,70],[80,90,100],[200,300,400]])

In [84]:
a

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100],
       [200, 300, 400]])

In [85]:
# finding array attributes
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

12
(4, 3)
2
int64


In [11]:
print(A.size)
print(A.shape)
print(A.ndim)
print(A.dtype)

6
(2, 3)
2
int64


### Section 1.3. Array Operations

In [ ]:
# Reshaping arrays

In [86]:
a.shape

(4, 3)

In [15]:
Aa=np.reshape(A,(3,2))

In [16]:
Aa

array([[ 5, 10],
       [15, 10],
       [20, 30]])

In [95]:
b=np.reshape(a,(2,6))
b

array([[ 20,  30,  40,  50,  60,  70],
       [ 80,  90, 100, 200, 300, 400]])

In [97]:
# What does this do?
b=np.reshape(a,(2,-1))

In [104]:
b.shape

(2, 6)

In [99]:
b

array([[ 20,  30,  40,  50,  60,  70],
       [ 80,  90, 100, 200, 300, 400]])

In [105]:
# nesting operations in one line is common in this course
d = np.arange(0.0, 1000.0, 1.0).reshape(10,-1) 

In [106]:
d.shape

(10, 100)

In [107]:
d

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
         44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
         55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
         66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
         77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
         88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
         99.],
       [100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
        111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
        122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
        133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
        144., 145., 146

## Self Learning 1: Take this online tutorial

Try to develp your notebook likewise and experiment with various numpy functionalities
https://cs231n.github.io/python-numpy-tutorial/#numpy


## Self Learning 2: Watch and implemt this tutorial

Watch up to time 10:30 in the video to cover the numpy basics
https://www.youtube.com/watch?v=AAS8yoKuK7M