## Introduction to Python
## JN1

## Basic Jupyter

In [1]:
#code line
print
print('Welcome to GISC405')

Welcome to GISC405


In [2]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [3]:
###use show contextual help
print("Welcome to GISC405")

Welcome to GISC405


# Section 1. Basic Python

### Section 1.1. Basic Arithmetic Operations

In [156]:
a = 3

In [157]:
a

3

In [158]:
b = 2

In [159]:
a**b

9

In [160]:
a*b

6

In [161]:
c = a**b
d = a*b

In [1]:
v = 3**2

In [2]:
print(v)

9


In [162]:
print('square of',a,'is',c)
print(a,'multipled by',b, "is",d )

square of 3 is 9
3 multipled by 2 is 6


In [163]:
5//4

1

In [164]:
5/4

1.25

In [165]:
int(5/4)

1

In [166]:
int?

Init signature: int(self, /, *args, **kwargs)
Docstring:     
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4
Type:           type
Subclasses:     bool, IntEnum, IntFlag, _NamedIntConstant


In [167]:
5.5//4 # Can someone tell me what this oepration does?

1.0

In [168]:
7%4 # Can someone tell me what this operation does?

3

In [169]:
7//4

1

In [170]:
a = list([1,[2,3]]) # A list in Python is a collectoon of different "objects" or variables with different data types

In [171]:
a[1]

[2, 3]

In [172]:
a

[1, [2, 3]]

In [173]:
a = list(['kit','marwan', 'sky'])

In [174]:
a[2]

'sky'

In [175]:
len(a)  # len, short for lenght, returns the number of items in the list

3

In [176]:
len("12345")

5

In [4]:
b = dict([('kit', 5), ('sky', 'newstudent'), ('marwan', -5)])  # A dictionary stores values into specific variable names that can be called directly form the list

In [178]:
b['sky']

'newstudent'

In [7]:
# Dictionaries can also be set using braces {} without invoking the function "dict"
MetData={'Temperature':[20,15,18],'Wind Speed':[3,6,10]}

In [180]:
MetData['Temperature'] # calling a specific part of the dictionary

[20, 15, 18]

In [ ]:
b['x']  # calling a specific part of the dictionary

### Section 1.2. Conditional Statements

In [ ]:
a = 3
b = 2

In [ ]:
if (a > 3):
    e = a
elif (a < 3):
    e = 3
else:
    e = 0

In [ ]:
e

In [ ]:
if (a > 3) and (b <=2):
    e = a + b

In [ ]:
e

In [2]:
gisc_405 = 99

Other conditional statements include switch/case pairs and won't be discussed here since we won't use it for this course.

### Section 1.3. Loop Statements

In [ ]:
a = 0

In [ ]:
for i in range(0,10):  # looping the index i from 0 to 10 in steps of 1
    a = a + i

In [ ]:
list(range(0,10))

In [ ]:
range?

In [ ]:
a

In [ ]:
b = 0

In [ ]:
i = 0
while i < 10:
    b = b+i
    i=i+1

In [ ]:
b

### Section 1.4. Defining a Function

In [3]:
def add_two(a,b):
    c = a + b
    return c

In [4]:
c=add_two(10,20)

In [5]:
c

30

In [ ]:
a=[3,4,5]
b=[10,20,30]
c=a[0]+b[0]
#c =add_two(a,b)

In [ ]:
c

### Section 1.5. Task
Write a function (gisc_exponential) to calculate the exponential of a variable with the base of Euler’s number. Return 0 if the result is smaller than 0.1.

Note: check your python reference card on Larn resources to find the exponential function

In [ ]:
def gisc_exponential(x):
    E=2.718281828459045**x
    if E<=0.1:
        return E
    else:
        print("Your exponent is not less than 0.1")
        return E
        
# print("The Euler's base exponent of",x,"is:",gisc_exponential(x))

In [ ]:
gisc_exponential(3)

# Section 2. Matrix Manipulation
Numpy is "The fundamental package for scientific computing with Python". (https://numpy.org)

### Section 2.1. Importing Libraries

In [ ]:
### Libraries are existing packages of functions/classes written by you or someone else. You can utilize the existing functions to speed up your work.

In [13]:
import numpy as np # import all the library

In [14]:
from numpy import sqrt as npsqrt # import a specific operation

In [ ]:
np.sqrt(10) # personally I like this way...

In [ ]:
np.sqrt(16)

### Section 2.2. Creating a Matrix

In [15]:
a = np.arange(0,1000,1)

In [16]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
np.sqrt(a)

In [ ]:
a.shape

In [ ]:
b=np.reshape(a,(10,-1))

In [ ]:
b.shape

In [ ]:
b

In [ ]:
c = np.zeros((10,5))

In [ ]:
c

In [ ]:
D=[[1, 2, 3, 4],[10, 20, 30, 40],[50, 60, 70, 80]]  # matrices can deifned by direct assignment

In [ ]:
np.shape(D)

### Section 2.3. Matrix Operations

In [ ]:
d = np.arange(0.0, 1000.0, 1.0).reshape(10,-1) # nesting operations in one line is common in this course

In [ ]:
d.shape

In [ ]:
d

In [ ]:
d.dtype

In [ ]:
b.dtype

In [ ]:
b.shape

In [ ]:
d.shape

In [ ]:
np.multiply(b,d) # Linear algebra rule for mulitplying

In [ ]:
b*d # direct one-to-one multiplication, better suted for geospatial data operations, why?

In [ ]:
np.matmul(b,d.transpose())

### Section 1.5. Task
Try to use the function you wrote (gisc_exponential) from the above with the numpy array (b), will it work?
Rewrite the function using numpy function np.exp
Can you use an array as input to the function this time?

In [17]:
def gisc_exponential(x):
    E=2.718281828459045**x
    if E<=0.1:
        return E
    else:
        print("Your exponent is not less than 0.1")
        return E
        
# print("The Euler's base exponent of",x,"is:",gisc_exponential(x))

In [25]:
B1=gisc_exponential(3)

Your exponent is not less than 0.1


In [22]:
b=np.arange(0,12,0.5).reshape(12,-1)
np.shape(b)

(12, 2)

In [26]:
E=np.exp(b)

In [27]:
E.shape

(12, 2)

In [28]:
E

array([[1.00000000e+00, 1.64872127e+00],
       [2.71828183e+00, 4.48168907e+00],
       [7.38905610e+00, 1.21824940e+01],
       [2.00855369e+01, 3.31154520e+01],
       [5.45981500e+01, 9.00171313e+01],
       [1.48413159e+02, 2.44691932e+02],
       [4.03428793e+02, 6.65141633e+02],
       [1.09663316e+03, 1.80804241e+03],
       [2.98095799e+03, 4.91476884e+03],
       [8.10308393e+03, 1.33597268e+04],
       [2.20264658e+04, 3.63155027e+04],
       [5.98741417e+04, 9.87157710e+04]])

In [29]:
E<10

array([[ True,  True],
       [ True,  True],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [30]:
np.where(E<10,0,100)

array([[  0,   0],
       [  0,   0],
       [  0, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100]])

In [269]:
b

array([[ 0. ,  0.5],
       [ 1. ,  1.5],
       [ 2. ,  2.5],
       [ 3. ,  3.5],
       [ 4. ,  4.5],
       [ 5. ,  5.5],
       [ 6. ,  6.5],
       [ 7. ,  7.5],
       [ 8. ,  8.5],
       [ 9. ,  9.5],
       [10. , 10.5],
       [11. , 11.5]])

In [301]:
def gisc_exponential_V2(x):
    E=np.exp(x)
    E_new=np.where(E<10,0,E)
    return E_new

In [302]:
gisc_exponential_V2(b)

array([[0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.21824940e+01],
       [2.00855369e+01, 3.31154520e+01],
       [5.45981500e+01, 9.00171313e+01],
       [1.48413159e+02, 2.44691932e+02],
       [4.03428793e+02, 6.65141633e+02],
       [1.09663316e+03, 1.80804241e+03],
       [2.98095799e+03, 4.91476884e+03],
       [8.10308393e+03, 1.33597268e+04],
       [2.20264658e+04, 3.63155027e+04],
       [5.98741417e+04, 9.87157710e+04]])